const GasPlugin = require("gas-webpack-plugin");
const webpack = require("webpack");

module.exports = {
  // we always use dev mode because bundle size is unimportant - code runs server-side
  mode: "development",
  context: __dirname,
  entry: "./build/index.js",
  output: {
    path: __dirname,
    filename: "Code.js",
  },
  plugins: [
    new GasPlugin({
      autoGlobalExportsFiles: ["./build/index.js"],
    }),
    new webpack.BannerPlugin({
      banner: `Vacation Calendar (https://github.com/iansan5653/vacation-calendar-addon)
Copyright 2024 Ian Sanders, released under MIT license
---

Do not edit this file directly. Instead, contribute to the source code in the linked repository.`,
    }),
  ],
  devtool: false,
};
